### ISSUE TITLE
ghc: user error (user error (Path is unchanged, nothing to do.))

### ISSUE THREAD

**Issue by RyanGlScott** [ku-fpg/hermit#116]
In my attempt to fix up HERMIT for GHC 7.6 (see the [ghc-7.6 branch](https://github.com/ku-fpg/hermit)), I stumbled across this runtime error:
```
$ hermit examples/last/Last.hs
[starting HERMIT v0.5.0.0 on examples/last/Last.hs]
% ghc examples/last/Last.hs -fforce-recomp -O2 -dcore-lint -fsimple-list-literals -fexpose-all-unfoldings -fplugin=HERMIT -fplugin-opt=HERMIT:*:
[1 of 1] Compiling Main             ( examples/last/Last.hs, examples/last/Last.o )
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package array-0.4.0.1 ... linking ... done.
Loading package deepseq-1.3.0.1 ... linking ... done.
Loading package containers-0.5.0.0 ... linking ... done.
Loading package filepath-1.3.0.1 ... linking ... done.
Loading package old-locale-1.0.0.5 ... linking ... done.
Loading package time-1.4.0.1 ... linking ... done.
Loading package bytestring-0.10.0.2 ... linking ... done.
Loading package unix-2.6.0.1 ... linking ... done.
Loading package directory-1.2.0.1 ... linking ... done.
Loading package binary-0.5.1.1 ... linking ... done.
Loading package old-time-1.1.0.1 ... linking ... done.
Loading package pretty-1.1.1.0 ... linking ... done.
Loading package process-1.1.0.2 ... linking ... done.
Loading package Cabal-1.16.0 ... linking ... done.
Loading package bin-package-db-0.0.0.0 ... linking ... done.
Loading package hoopl-3.9.0.0 ... linking ... done.
Loading package hpc-0.6.0.0 ... linking ... done.
Loading package template-haskell ... linking ... done.
Loading package ghc-7.6.3 ... linking ... done.
Loading package ansi-terminal-0.6.1.1 ... linking ... done.
Loading package data-default-class-0.0.1 ... linking ... done.
Loading package data-default-instances-base-0.0.1 ... linking ... done.
Loading package data-default-instances-containers-0.0.1 ... linking ... done.
Loading package dlist-0.7.0.1 ... linking ... done.
Loading package data-default-instances-dlist-0.0.1 ... linking ... done.
Loading package data-default-instances-old-locale-0.0.1 ... linking ... done.
Loading package data-default-0.5.3 ... linking ... done.
Loading package terminfo-0.4.0.0 ... linking ... done.
Loading package transformers-0.4.1.0 ... linking ... done.
Loading package haskeline-0.7.1.3 ... linking ... done.
Loading package kure-2.16.2 ... linking ... done.
Loading package marked-pretty-0.1 ... linking ... done.
Loading package mtl-2.2.1 ... linking ... done.
Loading package random-1.0.1.1 ... linking ... done.
Loading package operational-0.2.3.2 ... linking ... done.
Loading package stm-2.4.3 ... linking ... done.
Loading package exceptions-0.6.1 ... linking ... done.
Loading package temporary-1.2.0.3 ... linking ... done.
Loading package hermit-0.5.0.0 ... linking ... done.
ghc: user error (user error (Path is unchanged, nothing to do.))
```
[Here](https://github.com/ku-fpg/hermit/commit/7b8d92b96295dbf11aa4b1cb07a53b4a02c566ce) are the changes I made.

**Comment by RyanGlScott** [comment]
I've been trying to go through HERMIT and replace all uses of `ErrorT` with `ExceptT` (using the [`transformers-compat`](http://hackage.haskell.org/package/transformers-compat) package), and I noticed that when I replace everything `ErrorT`-related with `ExceptT` in `HERMIT.Plugin.Types`, that alone is enough to trigger this error when running any example.

Therefore, it's possible that GHC HEAD isn't the problem, but rather the recent versions of `mtl` and `transformers`. It's rather difficult to test with the latest versions of those packages on GHC 7.8, since `transformers-0.3.0.0` is a dependency of `ghc-7.8`.

**Comment by RyanGlScott** [comment]
I think I've finally figured out the issue. I noticed that this piece of code from `HERMIT.Plugin.Types`:

```haskell
instance Monad m => MonadCatch (PluginT m) where
    -- law: fail msg `catchM` f == f msg
    -- catchM :: m a -> (String -> m a) -> m a
    catchM m f = do
        st <- get
        (r,st') <- lift $ runPluginT st m
        
        case r of
            Left err -> traceShowM err >> case err of
                            PError msg -> undefined
                            other -> throwError other -- rethrow abort/resume
            Right v  -> put st' >> return v
```

behaves differently depending on which version of `transformers` is used. With `transformers-0.3.0.0`, `r` is `Left (PError "user error (Path is unchanged, nothing to do.)")`, as expected. With `transformers-0.4.2.0` (or `transformers-compat`), however, this code is never reached. That's because GHC is throwing an error message before then; specifically, from this code in `HERMIT.Kernel.Scoped`:

```haskell
scopedKernel :: (ScopedKernel -> SAST -> IO ()) -> ModGuts -> CoreM ModGuts
scopedKernel callback = ...
    let skernel = ScopedKernel {
        ...
    , modPathS    = \ f env (SAST sAst) -> safeTakeTMVar store $ \ m -> do
                                (ast, base, rel) <- get sAst m
                                let rel' = f rel
                                queryK kernel ast (testPathStackT base rel') env
                                  >>= runKureM (\ b -> if rel == rel'
                                                        then fail "Path is unchanged, nothing to do."
                                                        else if b
                                                              then atomically $ do k <- newKey
                                                                                   putTMVar store $ I.insert k (ast, base, rel') m
                                                                                   return $ SAST k
                                                              else fail "Invalid path created.")
```

It seems that `fail "Path is unchanged, nothing to do."` is causing GHC is throw the error. This surprised me since I thought `ExceptT` behaved identically to `ErrorT`, but as it turns out, that's not true. There's a subtle difference in the `Monad` instances for the two classes:

```haskell
instance (Monad m, Error e) => Monad (ErrorT e m) where
    ...
    fail msg = ErrorT $ return (Left (strMsg msg))


instance (Monad m) => Monad (ExceptT e m) where
    ...
    fail = ExceptT . fail
```

When `fail` returns an `ErrorT`, it always returns a `Left` value, which is why HERMIT wouldn't crash. With `ExceptT`, however, it returns an `Either` using `fail`, and since `Either`'s `Monad` instance doesn't implement `fail`, it defaults to calling `error`.

Now, having said all that, I'm not sure what the best approach to fixing this is. `modPathS` has to return something of type `m SAST`, so we can't just replace `fail` with `throwError`. Perhaps we need to be calling `catchError` in more places?

**Comment by xich** [comment]
Thanks for tracking this down!

It looks like we should be using `throwE` instead of `fail`. From the new transformers code:

```
-- | Signal an exception value @e@.
--
-- * @'runExceptT' ('throwE' e) = 'return' ('Left' e)@
--
-- * @'throwE' e >>= m = 'throwE' e@
throwE :: (Monad m) => e -> ExceptT e m a
throwE = ExceptT . return . Left
```

To avoid changing code everywhere, I expect it might be easier to write our own `Monad` instance for `PluginT`, rather than deriving it*, because then we can define `fail` in the `PluginT` monad to call `throwE`.

* https://github.com/ku-fpg/hermit/blob/master/src/HERMIT/Plugin/Types.hs#L34

**Comment by xich** [comment]
Also, we should pre-emptively fix this anywhere else we use `ExceptT`.

**Comment by xich** [comment]
The monad instance should be pretty simple... something like:

```haskell
instance Monad m => Monad (PluginT m) where
  return = PluginT . return
  (PluginT m) >>= k = PluginT (m >>= unPluginT . k)
  fail msg = PluginT . throwE . PError
```

**Comment by RyanGlScott** [comment]
That suggestion sounds pretty reasonable. I'll try to fix this up for `PluginT` and `CLT` (since I believe those are the only monad transformer stacks we use that have `ExceptT` as a layer).

**Comment by RyanGlScott** [comment]
Closed in d476036f71b09e10fc20a93bba10d44afb385115.

**Comment by xich** [comment]
Just curious, what version of mtl and transformers comes with 7.10? If they are sufficiently high to avoid the CPP, lets remember to bump their bounds and remove the CPP once 7.10 is in the Haskell Platform. (Our version policy is to support whatever GHC is in the Platform + newer versions.)

**Comment by xich** [comment]
Also, don't forget to remove that extra `print` call I commented on... otherwise diff looks great!

**Comment by RyanGlScott** [comment]
`ghc-7.10` itself has `transformers-0.4.2.0` as a dependency, so barring any new major versions of either package, we should be able to use the latest versions of `transformers` and `mtl` in the next version of HERMIT. That's what I'm doing right now in the [experimental GHC 7.10 HERMIT branch](https://github.com/ku-fpg/hermit/tree/ghc-7.10), which as of that bugfix, seems to work.
