### ISSUE TITLE
Interactive shell fails to parse names that include literal syntax

### ISSUE THREAD

**Issue by ecaustin** [ku-fpg/hermit#125]
When working with a module that contains bindings with names that include literal syntax, e.g. `$fMonad[] ∷ Monad []`, you cannot interact with those bindings by name.

Attempting to do so throws an expression type checking error:
`hermit<0> binding-of '$fMonad[]`
`Error in expression: binding-of '$fMonad []`
`Does not type-check: binding-of '$fMonad []`

The parser separates the literal syntax from the name, creating an ill-typed application.

**Comment by andygill** [comment]
Have you tried

    binding-of "$fMonad[]"

**Comment by ecaustin** [comment]
Yup, that works if you prepend the string with the tick operator to signal that it's a name, i.e. `binding-of '"$fMonad[]"`.

I'll leave it up to you if you want to close the issue or not depending on how hard the fix is to not require double-quotes.

**Comment by xich** [comment]
The double quotes solution was a quick fix at one point (for the SYB stuff)
that never got properly fixed. All the parsers (especially for Core) need
rewriting/expanding.

**Comment by ecaustin** [comment]
I'm going to close this since the new shell requires string-like names which is a known work-around to this issue.
