### ISSUE TITLE
`reflexivity` pattern match failure

### ISSUE THREAD

**Issue by roboguy13** [ku-fpg/hermit#130]
In proof mode, if you apply the proof command `reflexivity` on something that doesn't have the form of an equality, you get a pattern match failure on [this line](https://github.com/ku-fpg/hermit/blob/c9bdaef63a05ece4cea7d483935b52dd33b19343/src/HERMIT/Dictionary/Reasoning.hs#L355). The REPL doesn't crash, but it would be good to have a nicer message.

For example, if I run `cd examples/reverse ; hermit HList.hs`, I can get the following REPL session:

```
module HList where
  absH ∷ ∀ a . H a → [a]
  repH ∷ ∀ a . [a] → [a] → [a]
hermit<0> rule-to-lemma "repH ++"
repH ++ (Not Proven)
  ∀ △ xs ys. repH ▲ ((++) ▲ xs ys) ≡ (.) ▲ ▲ ▲ (repH ▲ xs) (repH ▲ ys)
hermit<1> prove-lemma "repH ++"
Goal:
  ∀ △ xs ys. repH ▲ ((++) ▲ xs ys) ≡ (.) ▲ ▲ ▲ (repH ▲ xs) (repH ▲ ys)
proof<2> reflexivity
Error in expression: reflexivity
Pattern match failure in do expression at src/HERMIT/Dictionary/Reasoning.hs:355:5-17
proof<2> 
```

**Comment by xich** [comment]
Fixed in be96fa6d66deebefd001dd668664c7ceee78b3b0
