### ISSUE TITLE
Inefficient childL implementations in HERMIT.Kure Walker instances

### ISSUE THREAD

**Issue by roboguy13** [ku-fpg/hermit#133]
As mentioned in https://github.com/ku-fpg/kure/issues/2#issuecomment-120145133, the implementations of `childL` in the HERMIT `Walker` instances are inefficient.

One practical problem that this causes is that we get a lot of unnecessary `there is no child matching the crumb.` error messages if (for instance) a `catchesT` call completely fails (due to user error). Using the `examples/laws/ListLaws.hs` example from ku-fpg/hermit-shell#23 with the new error reporting in `(<+)` we end up with this output:

> HERMIT> eval "rule-to-lemma nil-append"
> nil-append (Not Proven)
>   ∀ △ xs. (++) ▲ ([] ▲) xs ≡ xs
> [Done]
> 
> HERMIT> proveLemma "nil-append"
> Goal:
>   ∀ △ xs. (++) ▲ ([] ▲) xs ≡ xs
> [Done]
> 
> HERMIT> rhsR unfold
> (there is no child matching the crumb. <+ (there is no child matching the crumb. <+ (there is no child matching the crumb. <+ (there is no child matching the crumb. <+ (there is no child matching the crumb. <+ (there is no child matching the crumb. <+ (unfold failed: (not an application. <+ Inline failed: variable is not bound to an expression.) <+ (there is no child matching the crumb. <+ catchesT failed))))))))
> *** Exception: failed to parse result value for rewrite (rhs unfold ): Null : Object not returned from Server
> HERMIT> 

There is a message in there saying `unfold failed: (not an application. <+ Inline failed: variable is not bound to an expression.)` but it is hard to see with all the crumb errors.

**Comment by Sculthorpen** [comment]
It's looking like the definition of childL isn't the cause of the large number of "crumb" messages, but rather something that calls childL repeatedly without providing it's own error message.

childL is inefficient, but unless there's a significant gain I'm not sure it's worth overriding it, as that's a lot of (potentially error-prone) code.

**Comment by roboguy13** [comment]
Ahh, I see. So, should this be marked as "wontfix" and closed?

**Comment by Sculthorpen** [comment]
I think so.
