### ISSUE TITLE
CommitMsg?

### ISSUE THREAD

**Issue by conal** [ku-fpg/hermit#165]
When using `apply` from `HERMIT.Plugin`, what does the `CommitMsg` parameter mean?

**Comment by xich** [comment]
Sorry, forgot to reply to this.

The `CommitMsg` argument specifies whether to record the rewrite in the history tree. If you don't care about being able to use step/goto/etc, you can pass `Never`. `Always` causes an entry to be added even if nothing changes, `Changed` only adds an entry if something changes.

There is probably a better abstraction there... it was mostly hacked in during the run up to our last paper.

**Comment by conal** [comment]
Ah. Sounds like it's relevant some HERMIT territory I haven't discovered yet. Thanks for the explanation.
