### ISSUE TITLE
doesn't build on ghc 7.10.3

### ISSUE THREAD

**Issue by cartazio** [ku-fpg/hermit#174]
```
Building hermit-1.0.0.0...
Preprocessing library hermit-1.0.0.0...
[ 1 of 69] Compiling HERMIT.Syntax    ( src/HERMIT/Syntax.hs, dist/build/HERMIT/Syntax.o )
[ 2 of 69] Compiling HERMIT.Parser    ( dist/build/HERMIT/Parser.hs, dist/build/HERMIT/Parser.o )
[ 3 of 69] Compiling HERMIT.GHC.Typechecker ( src/HERMIT/GHC/Typechecker.hs, dist/build/HERMIT/GHC/Typechecker.o )

src/HERMIT/GHC/Typechecker.hs:151:34:
    Couldn't match expected type ‘RealSrcSpan’
                with actual type ‘SrcSpan’
    In the ‘tcl_loc’ field of a record
    In the expression:
      TcLclEnv
        {tcl_errs = errs_var,
         tcl_loc = mkGeneralSrcSpan (fsLit "Top level"), tcl_ctxt = [],
         tcl_rdr = emptyLocalRdrEnv, tcl_th_ctxt = topStage,
         tcl_th_bndrs = emptyNameEnv, tcl_arrow_ctxt = NoArrowCtxt,
         tcl_env = emptyNameEnv, tcl_bndrs = [], tcl_tidy = emptyTidyEnv,
         tcl_tyvars = tvs_var, tcl_lie = lie_var, tcl_tclvl = topTcLevel}
Updating documentation index


```

**Comment by RyanGlScott** [comment]
Thanks for noticing that, @cartazio. The Hackage version of `hermit` hasn't been updated since GHC 7.10.1, and GHC 7.10.2 made some pretty important changes involving `TcLclEnv` (to allow threading of `CallStack` information, IIRC).

@xich, do you think the current state of `hermit` is ready for another Hackage release? I'd do so myself, but I'm not in the maintainer group at the moment.

**Comment by xich** [comment]
@RyanGlScott Yes, we should do a release (1.1.0.0) for 7.10.3.

There are still some outstanding issues to solve for GHC 8, so if you do a release (I added you to the maintainer group, but don't feel obligated), please constrain the version of the 'ghc' package to '== 7.10.3'. (7.10.1 and 7.10.2 were broken anyway.)

If you don't release it, I can probably find some time later tonight.

@cartazio Thanks for pointing it out!

**Comment by cartazio** [comment]
sweet! 
I've never used hermit, but since some of the changes in 7.10.3 were aimed at making sure fusion (and hermit) worked, I figured I should try it out!

(also figured i should learn this whole rewrite based vocab engineering thingy)

**Comment by RyanGlScott** [comment]
Uploaded [`hermit-1.0.1`](http://hackage.haskell.org/package/hermit-1.0.1) to Hackage. Please reopen if there are any other installation issues.

**Comment by cartazio** [comment]
seems to build! I still need to try things out and stuff, but it installed!
